name: CI-CD
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-lastest
    steps:
      - run: echo "Obter o código"
      - run: echo "Executar Docker build"
      - run: echo "Enviar a Imagem Docker para o Docker Hub"
  CD:
    runs-on: ubuntu-lastest
    needs: [CI]
    steps:
      - run: echo "Obter o código"
      - run: echo "Configurar o Kubeconfig"
      - run: echo "Executar o apply"
